export const DATA_SOURCE = {
  REPOSITORIES: {
    WORD_DICTIONARY: 'WORD_DICTIONARY_REPOSITORY',
    USER: 'USER_REPOSITORY',
    USED_WORD: 'USED_WORD_REPOSITORY',
    TODO: 'TODO_REPOSITORY',
    TODO_FOLDER: 'TODO_FOLDER_REPOSITORY',
    REPORT: 'REPORT_REPOSITORY',
    POST: 'POST_REPOSITORY',
    MESSAGE: 'MESSAGE_REPOSITORY',
    LIKE: 'LIKE_REPOSITORY',
    GARDEN: 'GARDEN_REPOSITORY',
    FOLLOW: 'FOLLOW_REPOSITORY',
    COMMENT: 'COMMENT_REPOSITORY',
  },
  INJECT: 'DATA_SOURCE',
};
